#!/bin/bash
echo
echo "cpu health check:"
echo
mpstat
#iostat,top
echo
echo "memory usage"
echo
free -h
echo
echo "disk usage"
echo
df -h
echo
echo "network interface status and their throughput"
ifconfig
#ip -s link
echo

